### ISSUE TITLE
[Various] Add OneBus/VT system Emulation support.

### ISSUE THREAD

**Issue by TheRealHamtaro126** [emu-russia/breaknes#205]
https://www.nesdev.org/wiki/VTxx

Systems include VT02 (no extra RAM settings), VT03 (with cart SRAM enabled), VT09 (with internal RAM at $0000-$0FFF, and with cart SRAM enabled), and VT32 (Same RAM settings as VT09). maybe later for VT369 if figured out.

These settings are based on Nintendulator-NRS, so take it with a grain of salt.

**Comment by TheRealHamtaro126** [comment]
Hummer Team made enhanced consoles called the "VT series consoles" that enhance the graphics, RAM/ROM and sound of the NES/FC Hardware and Software. But the user must maintain the games themselves, as the stuff that are added for OneBus hardware use must be patched in the ROM or using source code. (Examples are Mostly homebrew titles from Hummer Team.)

**Comment by ogamespec** [comment]
Breaknes is designed for emulation of standard APU/PPU based systems only.
